### ISSUE TITLE
Dependabot yml config

### ISSUE THREAD

**Issue by bf4** [Shopify/bootboot#48]
I  haven't figured it out yet and if someone has, here may be a reasonable place for it to exist..  how someone might manage or configure a `.github/dependabot.yml` to handle both Gemfile.lock and Gemfile_next.lock?

```yaml
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
```

xref https://github.com/dependabot/dependabot-core/issues/3266
